Support for VaaS keystore
Venafi/vcert-java pull request #67
Opened 2021-11-23 17:50 UTC by marcos-albornoz

2021-11-23 18:18 UTC, angelmoo commented on src/main/java/com/venafi/vcert/sdk/connectors/cloud/CloudConnector.java
> +	    //zoneConfig.zoneId(zoneId);
could me remove this commented code...

2021-11-23 18:20 UTC, angelmoo commented on src/main/java/com/venafi/vcert/sdk/connectors/cloud/CloudConnector.java
> +			  //.zoneId(zoneConfiguration.zoneId());
please could we remove this comment.

2021-11-23 18:32 UTC, marcos-albornoz commented on src/main/java/com/venafi/vcert/sdk/connectors/cloud/CloudConnector.java
> +	    //zoneConfig.zoneId(zoneId);
it's done

2021-11-23 18:32 UTC, marcos-albornoz commented on src/main/java/com/venafi/vcert/sdk/connectors/cloud/CloudConnector.java
> +			  //.zoneId(zoneConfiguration.zoneId());
it's done

2021-11-23 19:57 UTC, rvelaVenafi approved these changes

2021-11-23 20:23 UTC, angelmoo requested changes

2021-11-23 20:23 UTC, angelmoo commented on src/main/java/com/venafi/vcert/sdk/connectors/cloud/SealedBoxUtility.java
> +	public static final int crypto_box_NONCEBYTES = 24;
I think we should use capital letters for this constants.

2021-11-23 20:23 UTC, angelmoo commented on src/main/java/com/venafi/vcert/sdk/connectors/cloud/SealedBoxUtility.java
> +	//public static final int crypto_box_PUBLICKEYBYTES = 32;
please could we remove this commented code....

2021-11-23 20:23 UTC, angelmoo commented on src/main/java/com/venafi/vcert/sdk/connectors/cloud/SealedBoxUtility.java
> +	public static byte[] crypto_box_seal(byte[] receiverPubKey, byte[] clearText) throws GeneralSecurityException {
For this Methods name we must follow camel case format.

2021-11-23 20:23 UTC, angelmoo commented on src/main/java/com/venafi/vcert/sdk/connectors/cloud/SealedBoxUtility.java
> +	public static byte[] crypto_box_seal_nonce(byte[] senderpk, byte[] mypk){
For this Methods name we must follow camel case format.

2021-11-23 20:23 UTC, angelmoo commented on src/main/java/com/venafi/vcert/sdk/connectors/cloud/SealedBoxUtility.java
> +		//final org.bouncycastle.jcajce.provider.digest.Blake2b blake2b = Blake2b.Digest.newInstance( crypto_box_NONCEBYTES );
could we remove this commented code.

2021-11-24 05:30 UTC, marcos-albornoz commented on src/main/java/com/venafi/vcert/sdk/connectors/cloud/SealedBoxUtility.java
> +	//public static final int crypto_box_PUBLICKEYBYTES = 32;
I prefer not to do it because those values can be used in the future as reference.

2021-11-24 05:30 UTC, marcos-albornoz commented on src/main/java/com/venafi/vcert/sdk/connectors/cloud/SealedBoxUtility.java
> +	public static final int crypto_box_NONCEBYTES = 24;
it's done

2021-11-24 05:30 UTC, marcos-albornoz commented on src/main/java/com/venafi/vcert/sdk/connectors/cloud/SealedBoxUtility.java
> +	public static byte[] crypto_box_seal(byte[] receiverPubKey, byte[] clearText) throws GeneralSecurityException {
It's done

2021-11-24 17:00 UTC, angelmoo approved these changes
changes looks good

2021-11-30 00:50 UTC, merged